name: build

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm ci
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Linter
        run: npm run lint
      - name: Test
        run: npm run test:ci
      - name: "Publish @paddls"
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-common"
          publish_args: "--access public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
      - name: "PrePublish @witty-services"
        uses: jossef/action-set-json-field@v1
        with:
          file: "./dist/ngx-common/package.json"
          field: name
          value: "@witty-services/ngx-common"
      - name: "Publish @witty-services"
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          commit_pattern: "^release: v(\\S+)"
          workspace: "./dist/ngx-common"
          publish_args: "--access public"
          create_tag: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN_PADDLS }}
